apiVersion: my.domain/v1alpha1
kind: Sleep
metadata:
  labels:
    app.kubernetes.io/name: admission-sleep-webhook
    app.kubernetes.io/managed-by: kustomize
  name: sleep-sample
spec:
  # TODO(user): Add fields here
