---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.18.0
  name: sleeps.my.domain
spec:
  group: my.domain
  names:
    kind: Sleep
    listKind: SleepList
    plural: sleeps
    singular: sleep
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Sleep is the Schema for the sleeps API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: SleepSpec defines the desired state of Sleep.
            properties:
              mutatingDuration:
                default: 0s
                description: |-
                  duration to sleep in the mutating webhook.
                  Example: "5s", "1m", "2h".
                pattern: ^([0-9]+[smh])+$
                type: string
              validatingDuration:
                default: 0s
                description: |-
                  duration to sleep in the validating webhook.
                  Example: "5s", "1m", "2h".
                pattern: ^([0-9]+[smh])+$
                type: string
            type: object
          status:
            description: SleepStatus defines the observed state of Sleep.
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
